### ISSUE TITLE
mailtrap.exceptions.AuthorizationError: Unauthorized

### ISSUE THREAD

**Issue by dervishali** [railsware/mailtrap-python#3]
Dear colleagues, 

I am trying to execute the minimal version of the e-mail sending Python codes you have shared below: 

---
import mailtrap as mt

# create mail object
mail = mt.Mail(
    sender=mt.Address(email="aliaciftci@gmail.com", name="Mailtrap Test"),
    to=[mt.Address(email="aliaciftci@gmail.com")],
    subject="You are awesome!",
    text="Congrats for sending test email with Mailtrap!",
)

# create client and send
client = mt.MailtrapClient(token="my token")
client.send(mail)
---
and I am receiving "mailtrap.exceptions.AuthorizationError: Unauthorized" error when I run the code. 

Any help and support will be appreciated. 

Regards, 

AAÇ

**Comment by VladimirTaytor** [comment]
Thanks for using our package, I would look what is going with your credentials, and let you know a bit later 👍 

Meanwhile, I would remove API token you provided from the message, as it's not secure to share it in public, please re-generate it asap 🙏

**Comment by VladimirTaytor** [comment]
Ok, I have checked your account, and looks like you want to use our Testing (Sandbox) functionality, but sadly our Python SDK supports only real emails sending (Sending) functionality. 

If you want to programatically send Testing emails please consider using `smtplib` from our examples in Mailtrap UI:
```python
import smtplib

sender = "Private Person <from@example.com>"
receiver = "A Test User <to@example.com>"

message = f"""\
Subject: Hi Mailtrap
To: {receiver}
From: {sender}

This is a test e-mail message."""

with smtplib.SMTP("sandbox.smtp.mailtrap.io", 2525) as server:
    server.login("your_login", "your_password")
    server.sendmail(sender, receiver, message)
```

, or HTTP API which is under active development at this moment:
- https://api-docs.mailtrap.io/docs/mailtrap-api-docs/bcf61cdc1547e-send-email-early-access
