### ISSUE TITLE
Send email template and add an attachment

### ISSUE THREAD

**Issue by jangita** [railsware/mailtrap-python#5]
Would it be possible to send an email using a template and add an attachment? Possibly have an attachments function argument?

**Comment by leonid-shevtsov** [comment]
Hello! Have you tried the `attachments` option to `MailFromTemplate`?

https://github.com/railsware/mailtrap-python/blob/main/mailtrap/mail/from_template.py#L15-L23

Alternatively, could you please post a code example for what you are trying to do?

**Comment by jangita** [comment]
Didn't see that as it is not in the documentation. And the support team only pushed me to the REST API and couldn't help with the python SDK.

Thank you for pointing this out. Should be good.

Best,

Chris.
